import { tailwindColorsType } from "../types/layouts.type";

const tailwindColorsList: tailwindColorsType[] = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
];

export const text500ColorsVariants = {
  slate: "text-slate-500",
  gray: "text-gray-500",
  zinc: "text-zinc-500",
  neutral: "text-neutral-500",
  stone: "text-stone-500",
  red: "text-red-500",
  orange: "text-orange-500",
  amber: "text-amber-500",
  yellow: "text-yellow-500",
  lime: "text-lime-500",
  green: "text-green-500",
  emerald: "text-emerald-500",
  teal: "text-teal-500",
  cyan: "text-cyan-500",
  sky: "text-sky-500",
  blue: "text-blue-500",
  indigo: "text-indigo-500",
  violet: "text-violet-500",
  purple: "text-purple-500",
  fuchsia: "text-fuchsia-500",
  pink: "text-pink-500",
  rose: "text-rose-500",
};

export const bg50ColorsVariants = {
  slate: "bg-slate-50",
  gray: "bg-gray-50",
  zinc: "bg-zinc-50",
  neutral: "bg-neutral-50",
  stone: "bg-stone-50",
  red: "bg-red-50",
  orange: "bg-orange-50",
  amber: "bg-amber-50",
  yellow: "bg-yellow-50",
  lime: "bg-lime-50",
  green: "bg-green-50",
  emerald: "bg-emerald-50",
  teal: "bg-teal-50",
  cyan: "bg-cyan-50",
  sky: "bg-sky-50",
  blue: "bg-blue-50",
  indigo: "bg-indigo-50",
  violet: "bg-violet-50",
  purple: "bg-purple-50",
  fuchsia: "bg-fuchsia-50",
  pink: "bg-pink-50",
  rose: "bg-rose-50",
};

export const bg100ColorsVariants = {
  slate: "bg-slate-100",
  gray: "bg-gray-100",
  zinc: "bg-zinc-100",
  neutral: "bg-neutral-100",
  stone: "bg-stone-100",
  red: "bg-red-100",
  orange: "bg-orange-100",
  amber: "bg-amber-100",
  yellow: "bg-yellow-100",
  lime: "bg-lime-100",
  green: "bg-green-100",
  emerald: "bg-emerald-100",
  teal: "bg-teal-100",
  cyan: "bg-cyan-100",
  sky: "bg-sky-100",
  blue: "bg-blue-100",
  indigo: "bg-indigo-100",
  violet: "bg-violet-100",
  purple: "bg-purple-100",
  fuchsia: "bg-fuchsia-100",
  pink: "bg-pink-100",
  rose: "bg-rose-100",
};

export const bg300ColorsVariants = {
  slate: "bg-slate-300",
  gray: "bg-gray-300",
  zinc: "bg-zinc-300",
  neutral: "bg-neutral-300",
  stone: "bg-stone-300",
  red: "bg-red-300",
  orange: "bg-orange-300",
  amber: "bg-amber-300",
  yellow: "bg-yellow-300",
  lime: "bg-lime-300",
  green: "bg-green-300",
  emerald: "bg-emerald-300",
  teal: "bg-teal-300",
  cyan: "bg-cyan-300",
  sky: "bg-sky-300",
  blue: "bg-blue-300",
  indigo: "bg-indigo-300",
  violet: "bg-violet-300",
  purple: "bg-purple-300",
  fuchsia: "bg-fuchsia-300",
  pink: "bg-pink-300",
  rose: "bg-rose-300",
};

export const bg500ColorsVariants = {
  slate: "bg-slate-500",
  gray: "bg-gray-500",
  zinc: "bg-zinc-500",
  neutral: "bg-neutral-500",
  stone: "bg-stone-500",
  red: "bg-red-500",
  orange: "bg-orange-500",
  amber: "bg-amber-500",
  yellow: "bg-yellow-500",
  lime: "bg-lime-500",
  green: "bg-green-500",
  emerald: "bg-emerald-500",
  teal: "bg-teal-500",
  cyan: "bg-cyan-500",
  sky: "bg-sky-500",
  blue: "bg-blue-500",
  indigo: "bg-indigo-500",
  violet: "bg-violet-500",
  purple: "bg-purple-500",
  fuchsia: "bg-fuchsia-500",
  pink: "bg-pink-500",
  rose: "bg-rose-500",
};

export default tailwindColorsList;
